---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: browser-ops
  namespace: moon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: browser-ops
  namespace: moon
rules:
- apiGroups:
  - moon.aerokube.com
  resources:
  - browsersets
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: browser-ops
  namespace: moon
roleRef:
  kind: Role
  name: browser-ops
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: browser-ops
  namespace: moon
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: browser-ops
  namespace: moon
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          serviceAccountName: browser-ops
          containers:
          - name: browser-ops
            image: quay.io/aerokube/browser-ops:2.2.1
            args:
            - default
          restartPolicy: Never
