---
{{- if .Values.moon.ingress }}
{{- if .Values.moon.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.moon.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.moon.ingress.ingressClassName }}
{{- if .Values.moon.ingress.tls }}
  tls:
{{ toYaml .Values.moon.ingress.tls | nindent 4 }}
{{- end }}
  rules:
  - host: {{ .Values.moon.ingress.host }}
    http:
      paths:
      {{- $releaseName := .Release.Name }}
      {{- range $v := .Values.moon.ingress.paths }}
      - path: {{ $v.path | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}
            port:
              number: {{ $v.port }}
      {{- end }}
{{- end }}
{{- end }}
