---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAnnotations }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.serviceLabels }}
  labels:
  {{- range $key, $value := .Values.serviceLabels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: "moon"
    protocol: TCP
    port: 4444
  - name: "moon-ui"
    protocol: TCP
    port: 8080
