name: build

on:
  push:
    branches:
      - master

jobs:
  build-chart:
    runs-on: ubuntu-latest
    if: github.repository == 'aerokube/charts'
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ci/test.sh

      - name: Build
        run: |
          git fetch --tags
          export VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-$(git rev-parse --short HEAD)
          ci/build.sh $VERSION unstable

      - name: Configure S3 credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Send output to S3 bucket
        working-directory: ./output
        run: aws s3 cp . --endpoint=${{ secrets.S3_ENDPOINT }}  s3://${{ secrets.S3_BUCKET_NAME }} --recursive --acl public-read